config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#splash_screen"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :books, only: [:index, :show, :new, :create, :update] do
    resources :collections, only: [:destroy, :create]
  end
  resources :collections, only: [:update]
  resources :series, only: [:show, :index]
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  get '/collections/:id/favorite', to: "collections#favorite", as: :favorite_collection
  get '/collections/:id/read', to: "collections#read", as: :read_collection
  get '/home', to: 'pages#home'
end

app/models/book.rb
require 'open-uri'
class Book < ApplicationRecord

  TYPES = ['Roman', 'Manga', 'BD', 'Poesie']

  # Active Records Associations
  belongs_to :serie, optional: true
  has_many :book_genres, dependent: :destroy
  has_many :genres, through: :book_genres
  has_many :collections
  has_many :users, through: :collections

  has_one_attached :cover_img

  # ActiveRecords Validations
  validates :title, presence: true, uniqueness: true
  validates :book_type, presence: true, inclusion: { in: Book::TYPES }

  # Search scopes
  scope :with_user_id, lambda{ |user_id| joins(:users).where(users: {id: user_id}) }
  scope :filtered_by_genre, lambda{ |genres| joins(:genres).where(genres: {name: genres}) }
  scope :favorite_books, lambda{where(collections: { is_favorited: true})}
  scope :read_books, lambda{ where(collections: {is_read: 'true'}) }

  # PGSearch Methods
  include PgSearch::Model
  multisearchable against: [:title, :author, :illustrator]

  pg_search_scope :global_search,
    against: [:title, :author, :illustrator],
    associated_against: {serie: :name},
    using: {trigram: {}, tsearch: {prefix: true}}

  def self.from_ISBN(isbn)
    book = Book.find_by(isbn: isbn)
    
    unless book
      book = Book.from_BNF(isbn)
    end

    unless book
      book = Book.from_OL(isbn)
    end
    return book
  end

  def self.from_BNF(isbn)
    base_url = "http://catalogue.bnf.fr/api/SRU?version=1.2&operation=searchRetrieve&query=bib.isbn any \"#{isbn}\""
    begin
      file = URI.open(base_url)
      doc = Nokogiri::XML(file)
      nmsp = doc.collect_namespaces

      new_book = Book.new({
        title: doc.xpath("//mxc:datafield[@tag='200']/mxc:subfield[@code='a']", nmsp).text,
        book_type: 'Roman',
        author: doc.xpath("//mxc:datafield[@tag='200']/mxc:subfield[@code='f']", nmsp).text,
        release: Date.new(doc.xpath("//mxc:datafield[@tag='210']/mxc:subfield[@code='d']", nmsp).text.match(/(\d{4})/)[1].to_i),
        edition: doc.xpath("//mxc:datafield[@tag='210']/mxc:subfield[@code='c']", nmsp).text,
        cover_url: "https://catalogue.bnf.fr/couverture?appName=NE&idArk=#{
          doc.xpath("//srw:recordData/mxc:record", nmsp).attribute('id').value
        }&couverture=1&largeur=400&hauteur=600",
        isbn: isbn
      })

      unless doc.xpath("//mxc:datafield[@tag='225']/mxc:subfield[@code='a']", nmsp).text.empty?
        serie = Serie.create_or_find_by(name: doc.xpath("//mxc:datafield[@tag='225']/mxc:subfield[@code='a']", nmsp).text)
        new_book.serie = serie
        new_book.serie_number = doc.xpath("//mxc:datafield[@tag='225']/mxc:subfield[@code='v']", nmsp).text.to_i
        # serie_name: doc.xpath("//mxc:datafield[@tag='225']/mxc:subfield[@code='a']", nmsp).text,
        # serie_number: doc.xpath("//mxc:datafield[@tag='225']/mxc:subfield[@code='v']", nmsp).text,
      end

      new_book.save!

      return new_book
    rescue
      return nil
    end
  end

  def self.from_OL(isbn)
    base_url = "https://openlibrary.org/isbn/#{isbn}.json"
    begin

      file = URI.open(base_url).read
      doc = JSON.parse(file)
      new_book = Book.new(title: doc["title"])
      new_book.author = doc["by_statement"]
      unless new_book.author
        author_doc = JSON.parse(URI.open("https://openlibrary.org#{doc["authors"][0]["key"]}.json").read)
        new_book.author = author_doc["name"]
      end

      if doc["series"]
        serie = Serie.create_or_find_by(name: doc["series"][0].split(',')[0])
        new_book.serie = serie
      end

      new_book.book_type = "Roman"
      new_book.cover_url = doc["covers"] ? "https://covers.openlibrary.org/b/id/#{doc["covers"][0]}-M.jpg" : nil
      new_book.description = doc["description"] if (doc["description"])
      new_book.release = doc["publish_date"] if (doc["publish_date"])
      new_book.edition = doc["publishers"][0] if (doc["publishers"])
      new_book.isbn = isbn

      new_book.save!

      return new_book
    rescue
      return nil
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :update]

  def show
    @collection = Collection.find_by(book_id: @book.id, user: current_user)

    respond_to do |format|
      format.html
      format.text do
        @book = @book.find_by(book_params)
        render partial: "partials/books/book_card_choice",
        locals: {book: @book, collection: Collection.new},
        formats: [:html]
      end
    end
  end

  def index
    @books = Book.all.limit(30)

    if params[:query].present?
      @books = Book.global_search(params[:query]).limit(30)
    end

    unless (params[:owned].present? && params[:owned] == 'false')
      @books = @books.with_user_id(current_user.id)
    end

    if (params[:favorite].present? && params[:favorite] == 'true')
      @books = @books.favorite_books
    end

    if params[:genres].present? && params[:genres] != ""
      @books = @books.filtered_by_genre(params[:genres].split(' '))
    end

    @books = @books.includes(:genres, :serie, :cover_img_blob)
    @books = @books.order(created_at: :desc)
    @genres = Genre.all

    respond_to do |format|
      format.html
      format.text { render partial: "partials/index_list", locals: {books: @books}, formats: [:html] }
    end
  end

  def new
    unless params[:title]
      @book = @book || Book.new
      @book.genres.build
    else
      @book = Book.find_by(isbn: params[:isbn])

      unless @book
        @book = Book.create!(
          book_type: 'Roman',
          title: params[:title],
          author: params[:author],
          release: params[:release].size == 4 ? Date.new(params[:release].to_i) : Date.parse(params[:release]),
          edition: params[:edition],
          isbn: params[:isbn],
          cover_url: params[:cover_url]
        )
        @book.serie = Serie.create_or_find_by!(name: params[:serieNames][0]) if params[:serieNames].present?

        if params[:genres].present?
          genre = Genre.find_or_create_by!(name: params[:genres])
          @book.genres << genre unless @book.genres.include?(genre)
        end
      end
    end

    respond_to do |format|
      format.html
      format.text do
          render partial: "partials/books/book_card_choice",
            locals: {book: @book, collection: Collection.new},
            formats: [:html]
      end
    end
  end

  def update
    if @book.update(book_params) && params[:book][:genre_ids]
      params[:book][:genre_ids][1..].each do |genre_id|
        genre = Genre.find(genre_id)
        @book.genres << genre unless @book.genres.include?(genre)
      end
    end
  end

  def create
    @book = Book.from_ISBN(book_params[:isbn])
    @collection = Collection.create(user: current_user, book: @book)

    if @book && @collection.persisted?
      notice = "Le livre #{@book.title} a été rajouté à ta bibliothèque"
      render partial: "shared/flashes",
        locals: {notice: notice},
        formats: [:html]
    else
      alert = "Le livre #{@book.title} n'a pas été rajouté à ta bibliothèque"
      @book = Book.new
      render partial: "shared/flashes",
        locals: {alert: alert},
        formats: [:html]
    end


  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def serie_params
    params.require(:serie).permit(:name)
  end

  def book_params
    params.require(:book).permit(
      :book_type,
      :title,
      :author,
      :illustrator,
      :serie_id,
      :serie_number,
      :description,
      :release,
      :edition,
      :cover_img,
      :isbn
    )
  end
end

app/views/partials/books/_book_card.html.erb
<%# Stimulus controller pour cacher et révéler les infos des bouquins %>
<div data-controller="book-content" data-action="click->book-content#visible">
  <%# Partie cachée de la carte, Stimulus target bookInfos %>
  <%= render 'partials/books/book_card_open', book: book, collection: collection %>
  <%# Partie visible par défaut, Stimulus target bookDefault %>
  <%= render 'partials/books/book_card_close', book: book, collection: collection %>
</div>

app/views/partials/books/_book_card_choice.html.erb
<%= render 'partials/books/book_card', book: book, collection: collection %>
<div data-controller='update-book'>
  <div class='d-flex justify-content-end'>
    <button class='edit-book' data-update-book-target='button' data-action='click->update-book#toggleForm'>
      <i class="fa-solid fa-pen"></i>
    </button>
  </div>
  <div class='d-none' data-update-book-target='form'>
    <%= simple_form_for book, method: :patch do |f| %>
      <%= f.input :book_type,
        label: 'Type',
        prompt: 'Choisissez un type..',
        collection: Book::TYPES
      %>
      <hr>
      <div class="form-block-description">
        <%= f.input :description, label: false, placeholder: 'Description', input_html: {class: 'mb-0 w-100 hello'} %>
      </div>
      <hr>
      <div class='genre-block'>
        <%= f.association :genres, as: :check_boxes,
          input_html: {class: 'book-genre-input-button'},
          item_wrapper_class: 'genre-wrapper'
        %>
      </div>
      <hr>
      <div class='add-btn' data-action='click->update-book#toggleForm'>
        <%= f.submit "OK", class:'add-book'%>
      </div>
    <% end %>
  </div>
  <hr>

</div>

app/views/partials/books/_book_card_close.html.erb
<div class="card-close book-card" data-book-content-target="bookDefault"  style="<%= 'background-color: #ededed;' if collection.nil? %>">
  <div class="book-img-close"><i class="fa-solid fa-book <%= book.book_type.downcase %>-icon"></i></div>
  <div class="book-info">
    <p class="book-title"><%= book.title %></p>
    <% if book.serie %>
      <p class="book-series-close">n°<%= book.serie_number %> - <%= book.serie.name %></p>
    <% end %>
  </div>
  <div class="book-actions-close">
    <% if collection && collection.id %>
      <%= render 'partials/collections/favorite_button', collection: collection %>
    <% else %>
        <button
          value="<%= book_collections_path(book) %>"
          type="submit"
          class="btn btn-add-collection"
          data-book-content-accept-param="plain"
          data-action="click->book-content#stop_bubbling click->book-content#addCollection click->serie#refresh">
          <i class="fa-solid fa-plus"></i>
        </button>
    <% end %>
  </div>
</div>

app/views/partials/books/_book_card_open.html.erb
<div class="card-open d-none book-card <%= book.book_type.downcase %>-border" data-book-content-target="bookInfos">
  <div class="book-thumbnail">
    <%# si le cover_url contient l'image | ajouté en dur dans les seeds %>
    <% if book.cover_url %>
      <%= image_tag book.cover_url%>
    <%# si le cover_img active storage contient l'image | créé à travers l'action create du controller %>
    <% elsif book.cover_img.attached? %>
      <%= cl_image_tag book.cover_img.key %>
    <% end %>
  </div>

  <div class="book-info">
      <div class="first-block-info">
        <p class="book-title"><%= book.title %></p>
        <hr class="hr">
        <%# Si série, il y a %>
        <% if book.serie %>
          <p class="book-series">n°<%= book.serie_number %> - <%= book.serie.name %></p>
        <% end %>
      </div>
      <div class="card-details">
      <hr class="hr">
        <small>
          <i><p class="book-author"><%= book.author %>, <%= book.illustrator %></p></i>
          <p class="book-details"><%= book.release.strftime('%Y') if book.release %> • <%= book.edition if book.edition %></p>
        </small>
        <div class="book-actions">
          <%= link_to book_path(book) do %>
            <button class="btn btn-details" data-action="click->book-content#stop_bubbling"><i class="fa-solid fa-circle-info"></i></button>
          <% end %>
          <% if collection && collection.id%>
            <%= render 'partials/collections/favorite_button', collection: collection %>
            <%= render 'partials/collections/read_button', collection: collection %>
          <% else %>
            <button
              value="<%= book_collections_path(book) %>"
              type="submit"
              class="btn btn-add-collection"
              data-book-content-accept-param="plain"
              data-action="click->book-content#stop_bubbling click->book-content#addCollection click->serie#refresh">
              <i class="fa-solid fa-plus"></i>
            </button>
          <% end %>
        </div>
      </div>
      <%# <hr class="hr"> %>
      <%# <div class="book-desc"> %>
        <%# <p><strong>Description :</strong> <%= book.description </p> %>
      <%# </div> %>
  </div>
  <div class="book-genre">
    <% book.genres.each do |genre| %>
      <span class="badge big-badge"><%= genre.name %></span>
    <% end %>
  </div>
</div>

app/views/partials/books/_book_card_portrait.html.erb
<div class="portrait">

  <div class="box-book-cover">
    <div class="book-cover">
      <% if book.cover_url %>
          <%= image_tag book.cover_url, class:"book-cover-img" %>
      <% elsif book.cover_img.attached? %>
          <%= cl_image_tag book.cover_img.key, class:"book-cover-img" %>
      <% end %>
      <div class="info-button">
        <i class="fa-solid fa-circle-info"></i>
      </div>
      <%# <% book.genres.each do |genre| %>
        <%# <span class="badge rounded-pill text-bg-primary"><%= genre.name </span> %>
      <%# <% end %>
    </div>
  </div>
  <div class="book-info-portrait">
    <p class="book-title-portrait"><%= book.title %></p>
    <% if book.serie %>
        <p class="book-series-portrait">N°<%= book.serie_number %> - <%= book.serie.name %></p>
    <% end %>
  </div>
</div>

app/views/partials/books/_new_book_form.html.erb
<%= simple_form_for book, html: { class: 'new-book-form' } do |f| %>
<hr>
  <div class="form-block">
    <div class="form-row">
      <div class="form-col-8">
        <%= f.input :book_type,
          label: 'Type',
          prompt: 'Choisissez un type..',
          collection: Book::TYPES,
          input_html: { data: { action:'change->new-book-form#toggle_illustrator' } }
        %>
      </div>
      <div class="form-col-4">
        <%= f.input :release,
          as: :integer,
          label: 'Sortie',
          placeholder: '2000',
          input_html: {value: 2000}
        %>
      </div>
    </div>

    <%= f.input :title,
      label: false,
      placeholder: 'Titre'
    %>
    <%= f.input :author,
      label: false,
      placeholder: 'Auteur.trice'
    %>
    <%= f.input :illustrator,
      label: false,
      placeholder: 'Illustrateur.trice',
      wrapper_html: {
        data: { new_book_form_target: 'illustrator' }
      }
    %>
    <%= f.input :edition, label: false, placeholder: 'Edition' %>
  </div>
<hr>
  <div class="form-block-description">
    <%= f.input :description, label: false, placeholder: 'Description', input_html: {class: 'mb-0 w-100 hello'} %>
  </div>
<hr>
  <div class='form-block'>
    <div class="form-row">
      <div class="form-col-8">
        <%= f.association :serie,
          label: 'Série',
          prompt: 'Ajouter une série...',
          input_html: { data: { action:'change->new-book-form#toggle_serie' } }
        %>
      </div>
      <div class="form-col-4">
        <%= f.input :serie_number, label: 'N°' %>
      </div>
    </div>
    <div class="form-container" data-new-book-form-target='serie'>
      <input class="form-control string optional" type="text" name="serie[name]" placeholder="Nom de la série">
    </div>
  </div>
<hr>
  <div class='genre-block'>
    <%= f.association :genres, as: :check_boxes,
      input_html: {class: 'book-genre-input-button'},
      item_wrapper_class: 'genre-wrapper'
    %>
  </div>
<hr>
  <div class="form-block">
    <%= f.input :cover_img, as: :file, label: 'Image de couverture', input_html: {class: 'mb-0'} %>
  </div>
<hr>
  <div class='add-btn'>
    <%= f.submit 'Ajouter', class:'add-book' %>
  </div>
<% end %>

app/views/partials/books/_new_book_search.html.erb
<div id="search-barcode-reader" data-controller="bar-code-reader">
  <form class="search-bar"
        action=""
        data-action="submit->bar-code-reader#fetchDbBooks">
    <input  type="search"
            data-bar-code-reader-target="search"
            placeholder="Rechercher par titre..." />
    <button type="submit"
            class="search-button"
            aria-label="Search">
      <i class="fa-solid fa-magnifying-glass"></i>
    </button>
    <a  class="btn btn-codebar"
        data-action="click->bar-code-reader#start"
        data-bar-code-reader-target="start">

        <i class="fa-solid fa-barcode"></i></a>

    <a  class="btn btn-codebar d-none"
        data-action="click->bar-code-reader#reset"
        data-bar-code-reader-target="reset">

        <i class="fa-solid fa-xmark"></i></a>
  </form>


  <div class="barcode-video-wrapper d-none" data-bar-code-reader-target="videoWrapper">
    <video id="barcode-video"></video>
  </div>


  <div id="tempbook-container" class="d-none" data-bar-code-reader-target="tempBook"></div>

  <div  class="alert alert-warning alert-dismissible fade show d-none"
        role="alert"
        data-bar-code-reader-target="alert">
    <button type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"></button>
  </div>

  <div id="sourceSelectPanel" data-bar-code-reader-target="sourceSelectPanel" style="display:none;">
    <label for="sourceSelect">Change video source:</label>
    <select id="sourceSelect" data-bar-code-reader-target="sourceSelect"></select>
  </div>
</div>