config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#splash_screen"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :books, only: [:index, :show, :new, :create, :update] do
    resources :collections, only: [:destroy, :create]
  end
  resources :collections, only: [:update]
  resources :series, only: [:show, :index]
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  get '/collections/:id/favorite', to: "collections#favorite", as: :favorite_collection
  get '/collections/:id/read', to: "collections#read", as: :read_collection
  get '/home', to: 'pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :collections, dependent: :destroy
  has_many :favorite_series, dependent: :destroy
  has_many :books, through: :collections
  has_many :series, through: :favorite_series, source: :serie
  has_many :books_series, through: :books, source: :serie

  validates :nickname, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.all
  end
end

app/views/users/index.html.erb
<div class="title-card">
  <%= image_tag "BookBuddy_logo.svg", alt: "Logo BookBuddy", class: "book"%>
  <h2 class="card-title">Utilisateurs</h2>
</div>

<div class="user-cards">
  <% @users.each do |current_user| %>
    <div class="user-card">
      <div class="user-info">
        <h2 class="user-name">Pierre Brossard</h2>
        <p class="user-email">Pilou@gmail.com</p>
      </div>
      <div class="user-actions">
        <%= link_to 'Show', user_path(current_user), class: 'btn btn-show' %>
        <%= link_to 'Edit', edit_user_path(current_user), class: 'btn btn-edit' %>
        <%= link_to 'Delete', user_path(current_user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-delete' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="title-card">
  <%= image_tag "BookBuddy_logo.svg", alt: "Logo BookBuddy", class: "book"%>
  <h2 class="card-title">Hello <%= current_user.nickname %> !</h2>
</div>
<div class="profile">
    <div class="user">
      <div class="avatar">
        <img src="avatar.jpg" alt="Avatar">
      </div>
      <div class="user-infos">
        <h2>Nickname</h2>
        <p>Email: example@example.com</p>
        <button class="edit-profile">Editer</button>
        <button class="delete-profile">Supprimer le profil</button>
      </div>
    </div>

    <div class="home-card">
  <h4>Bienvenue  <strong><%= current_user.nickname %></strong> ! <br>
  <span style="color: lightgrey; font-size: 0.9em;">Il y a <strong><%= current_user.books.count %> livres</strong> dans ta bibliothèque...</span></h4>
</div>

<div class="last-books settings">
  <h2><i class="fa-solid fa-chart-simple home-icon-settings"></i></i> <span style="text-decoration: underline;
                text-decoration-style: solid;
                text-decoration-color: grey;
                text-decoration-thickness: 0.4rem;
                text-underline-offset: 0.1rem;">Ta collection</span></h2>
  <div class="home-card-collection">
    <div class="home-card-collection-details">
      <div class="roman-count">
        <strong>Roman<br><%= current_user.books.where(book_type: 'Roman').count %></strong>
      </div>
      <div class="manga-count">
        <strong >Manga<br><%= current_user.books.where(book_type: 'Manga').count %></strong>
      </div>
        <div class="bd-count">
      <strong >BD<br><%= current_user.books.where(book_type: 'BD').count %></strong>
      </div>
        <div class="poesie-count">
      <strong >Poésie<br><%= current_user.books.where(book_type: 'Poesie').count %></strong>
      </div>
    </div>
  </div>
</div>

<div class="last-books">
  <h2><i class="fa-solid fa-heart home-icon-heart"></i></i> <span style="text-decoration: underline;
                        text-decoration-style: solid;
                        text-decoration-color: #FF6359;
                        text-decoration-thickness: 0.4rem;
                        text-underline-offset: 0.1rem;">Tes favoris</span></h2>
  <div class="last-books-cards">
    <% current_user.books.favorite_books('true', current_user).each do |book| %>
      <%= link_to book_path(book) do %>
        <%= render 'partials/books/book_card_portrait', book: book %>
      <% end %>
    <% end %>
  </div>
</div>


    <div class="transactions">
      <h2>Transactions</h2>
      <ul class="transaction-list">
        <li><span class="transaction-type borrowed">Emprunté</span>
          <ul class="borrowed">
            <li>Titre du livre emprunté</li>
          </ul>
        </li>
        <li><span class="transaction-type lent">Prêté</span>
          <ul class="lent">
            <li>Titre du livre prêté - Pierre</li>
            <li>Titre du livre prêté - Louis</li>
            <li>Titre du livre prêté - Renaud</li>
          </ul>
        </li>
      </ul>
    </div>
    </div>