config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#splash_screen"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :books, only: [:index, :show, :new, :create, :update] do
    resources :collections, only: [:destroy, :create]
  end
  resources :collections, only: [:update]
  resources :series, only: [:show, :index]
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  get '/collections/:id/favorite', to: "collections#favorite", as: :favorite_collection
  get '/collections/:id/read', to: "collections#read", as: :read_collection
  get '/home', to: 'pages#home'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<nav class="nav" data-controller="navbar">
  <ul class="nav-links">
    <li class="nav-item">
      <%= link_to home_path do %>
        <i data-navbar-home-value="/home" data-navbar-target="home" class="fa-solid fa-house"></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_book_path do %>
        <i data-navbar-newBook-value="/books/new" data-navbar-target="new" class="fa-solid fa-plus"></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to books_path do %>
        <i data-navbar-target="books" class="fa-solid fa-table-list"></i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to series_path do %>
        <i class="fa-solid fa-book" data-navbar-target="series"></i>
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_user_sign.html.erb
<div class="user-log-out">
  <%= button_to '<i class="fa-solid fa-right-from-bracket"></i>'.html_safe, destroy_user_session_path, method: :delete %>
  <%= link_to users_path do %>
    <i class="fa-solid fa-user"></i>
  <% end %>
</div>