config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#splash_screen"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :books, only: [:index, :show, :new, :create, :update] do
    resources :collections, only: [:destroy, :create]
  end
  resources :collections, only: [:update]
  resources :series, only: [:show, :index]
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  get '/collections/:id/favorite', to: "collections#favorite", as: :favorite_collection
  get '/collections/:id/read', to: "collections#read", as: :read_collection
  get '/home', to: 'pages#home'
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :user, uniqueness: {scope: :book}
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:update, :favorite, :read]
  skip_before_action :verify_authenticity_token, only: [:create]

  def update
    @collection.update(collection_params)
    redirect_to book_path(@collection.book)
  end

  def create
    @book = Book.find(params[:book_id])
    @collection = Collection.create(book: @book, user: current_user)
    respond_to do |format|
      format.html {
        flash.notice = "#{@book.title} has been created !"
        redirect_to book_path(@book)
      }
      format.text { render partial: 'partials/books/book_card', locals: {book: @book, collection: @collection}, formats: [:html] }
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @collection = Collection.find_by(book: @book, user_id: current_user)
    @collection.destroy
    redirect_to book_path(@book)
  end

  def favorite
    @collection.is_favorited = !@collection.is_favorited
    if @collection.save
      respond_to do |format|
        format.html
        format.text { render partial: 'partials/collections/favorite_button', locals: {collection: @collection}, formats: [:html] }
      end
    else
      render json: {error: 'temporary error message'}, status: :unprocessable_entity
    end
  end

  def read
    @collection.is_read = !@collection.is_read
    if @collection.save
      respond_to do |format|
        format.html { render json: {message: 'The favorite status has been updated'}, status: :accepted }
        format.text { render partial: 'partials/collections/read_button', locals: { collection: @collection }, formats: [:html] }
      end
    else
      render json: {error: 'temporary error message'}, status: :unprocessable_entity
    end
  end

  private

  def collection_params
    params.require(:collection).permit(:comment)
  end

  def set_collection
    @collection = Collection.find(params[:id])
  end
end

app/views/partials/collections/_collection_form.html.erb
<%= simple_form_for collection do |f| %>
  <%= f.label :comment, "Enter un commentaire" %>
  <%= f.input :comment, label: false %>
  <%= f.submit "Valider", class: "btn green-btn"%>
<% end %>

app/views/partials/collections/_favorite_button.html.erb
<button
  value="<%= favorite_collection_path(collection) %>"
  data-turbo-method="patch"
  type="submit"
  class="btn btn-favorite"
  data-book-content-target="favButton"
  data-action="click->book-content#stop_bubbling click->book-content#addFavorite">
    <% if collection.is_favorited %>
      <i class="fa-solid fa-heart"></i>
    <% else %>
      <i class="fa-regular fa-heart"></i>
    <% end %>
</button>

app/views/partials/collections/_read_button.html.erb
<button
  value="<%= read_collection_path(collection) %>"
  data-turbo-method="patch"
  type="submit"
  class="btn btn-read"
  data-action="click->book-content#stop_bubbling click->book-content#addAsRead">
  <% if collection.is_read %>
    <i class="fa-solid fa-circle-check"></i>
  <% else %>
    <i class="fa-regular fa-circle-check"></i>
  <% end %>
 </button>